# Do not edit this file.

import json
import torch
import random
import numpy as np
from dotmap import DotMap


def to_json(x, filepath: str):
  with open(filepath, 'w') as fp:
    json.dump(x, fp)


def from_json(filepath: str):
  with open(filepath, 'r') as fp:
    data = json.load(fp)
  return data


def load_config(config_path: str) -> DotMap:
  return DotMap(from_json(config_path))


def fix_random_seed(seed: int):
  random.seed(seed)
  np.random.seed(seed)
  torch.seed(seed)
